server:
  port: 9089

spring:
  cloud:
    zookeeper:
      connect-string: cn.dreamccc.club:2181
      enabled: true
      discovery:
        root: /meta
        metadata:
          id: ${spring.application.name}
          name: ${spring.application.name}
          type: S
          url: www.baidu.com

  application:
    name: server