server:
  port: 9001

spring:
  cloud:
    zookeeper:
      connect-string: cn.dreamccc.club:2181
      enabled: true
      discovery:
        root: /meta
        metadata:
          name: ${spring.application.name}
          type: CONTROL

  application:
    name: control
