server:
  port: 9021


spring:
  cloud:
    zookeeper:
      connect-string: cn.dreamccc.club:2181
      enabled: true
      discovery:
        root: /meta
        metadata:
          name: ${spring.application.name}
          type: SERVER

  application:
    name: server


logging:
  level:
    club.dreamccc: debug
